spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.47.5:3306/pn2?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
#    serverTimezone=UTC
    username: root
    password: csm123456

server:
  port: 9047

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.lwj.PaintNail.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
